apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "fullname" . }}-ui
    component: route-ui
  name: {{ template "fullname" . }}-ui-route
spec:
  host: {{ .Values.route.hostname }}
  port:
    targetPort: {{ .Release.Name }}-ui
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ template "fullname" . }}-ui
    weight: 100
  wildcardPolicy: None
