apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "fullname" . }}-server
  name: {{ template "fullname" . }}-openapi-route
spec:
  host: {{ .Values.route.openapiHostname }}
  path: /
  port:
    targetPort: {{ .Release.Name }}-server
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ template "fullname" . }}-server
    weight: 100
  wildcardPolicy: None