apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-liberty-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: open-liberty-operator
  template:
    metadata:
      labels:
        name: open-liberty-operator
    spec:
      serviceAccountName: open-liberty-operator
      containers:
        - name: open-liberty-operator
          image: openliberty/operator:0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "open-liberty-operator"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 3
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
