CONNECT TO PBW ; 
DROP TABLE APP.CUSTOMER;
DROP TABLE APP.INVENTORY;
DROP TABLE APP.ORDER1;
DROP TABLE APP.ORDERITEM;
DROP TABLE APP.IDGENERATOR;
DROP TABLE APP.BACKORDER;
DROP TABLE APP.SUPPLIER;
